// clang-format off

/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.0
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

/****************************************************************************
 Copyright (c) 2022-2023 Xiamen Yaji Software Co., Ltd.

 http://www.cocos.com

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights to
 use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
 of the Software, and to permit persons to whom the Software is furnished to do so,
 subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
****************************************************************************/

#if defined(__clang__)
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"
#elif defined(__GNUC__) || defined(__GNUG__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wunused-variable"
#elif defined(_MSC_VER)
#pragma warning(push)
#pragma warning(disable : 4101)
#endif


#define SWIG_STD_MOVE(OBJ) std::move(OBJ)


#include <stdio.h>


#include "bindings/jswrapper/SeApi.h"
#include "bindings/manual/jsb_conversions.h"
#include "bindings/manual/jsb_global.h"


#include "bindings/auto/jsb_blk_helper_auto.h"
// Add more includes in the generated source file bellow
// ...



se::Class* __jsb_blk_BlkHelper_class = nullptr;
se::Object* __jsb_blk_BlkHelper_proto = nullptr;
SE_DECLARE_FINALIZE_FUNC(js_delete_blk_BlkHelper) 

static bool js_new_blk_BlkHelper(se::State& s) // NOLINT(readability-identifier-naming)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    
    blk::BlkHelper *result;
    result = (blk::BlkHelper *)new blk::BlkHelper();
    
    
    auto *ptr = JSB_MAKE_PRIVATE_OBJECT_WITH_INSTANCE(result);
    s.thisObject()->setPrivateObject(ptr);
    return true;
}
SE_BIND_CTOR(js_new_blk_BlkHelper, __jsb_blk_BlkHelper_class, js_delete_blk_BlkHelper)

static bool js_delete_blk_BlkHelper(se::State& s)
{
    return true;
}
SE_BIND_FINALIZE_FUNC(js_delete_blk_BlkHelper) 

static bool js_blk_BlkHelper_print(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    blk::BlkHelper *arg1 = (blk::BlkHelper *) NULL ;
    
    if(argc != 0) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 0);
        return false;
    }
    arg1 = SE_THIS_OBJECT<blk::BlkHelper>(s);
    if (nullptr == arg1) return true;
    (arg1)->print();
    
    
    return true;
}
SE_BIND_FUNC(js_blk_BlkHelper_print) 

static bool js_blk_BlkHelper_pass(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    blk::BlkHelper *arg1 = (blk::BlkHelper *) NULL ;
    ccstd::vector< unsigned char > *arg2 = 0 ;
    ccstd::vector< unsigned char > temp2 ;
    
    if(argc != 1) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 1);
        return false;
    }
    arg1 = SE_THIS_OBJECT<blk::BlkHelper>(s);
    if (nullptr == arg1) return true;
    
    ok &= sevalue_to_native(args[0], &temp2, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    arg2 = &temp2;
    
    (arg1)->pass(*arg2);
    
    
    return true;
}
SE_BIND_FUNC(js_blk_BlkHelper_pass) 

static bool js_blk_BlkHelper_fillAsync(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    blk::BlkHelper *arg1 = (blk::BlkHelper *) NULL ;
    ccstd::vector< unsigned char > arg2 ;
    uint8_t arg3 ;
    uint32_t arg4 ;
    std::function< void (ccstd::vector< unsigned char >) > *arg5 = 0 ;
    float arg6 ;
    uint32_t arg7 ;
    std::function< void (ccstd::vector< unsigned char >) > temp5 ;
    
    if(argc != 6) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 6);
        return false;
    }
    arg1 = SE_THIS_OBJECT<blk::BlkHelper>(s);
    if (nullptr == arg1) return true;
    
    ok &= sevalue_to_native(args[0], &arg2, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments"); 
    
    
    ok &= sevalue_to_native(args[1], &arg3, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    
    
    ok &= sevalue_to_native(args[2], &arg4, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    
    
    ok &= sevalue_to_native(args[3], &temp5, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    arg5 = &temp5;
    
    
    ok &= sevalue_to_native(args[4], &arg6, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments"); 
    
    ok &= sevalue_to_native(args[5], &arg7, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    
    (arg1)->fillAsync(arg2,arg3,arg4,(std::function< void (ccstd::vector< unsigned char >) > const &)*arg5,arg6,arg7);
    
    
    return true;
}
SE_BIND_FUNC(js_blk_BlkHelper_fillAsync) 

static bool js_blk_BlkHelper_fill(se::State& s)
{
    CC_UNUSED bool ok = true;
    const auto& args = s.args();
    size_t argc = args.size();
    blk::BlkHelper *arg1 = (blk::BlkHelper *) NULL ;
    ccstd::vector< unsigned char > arg2 ;
    uint8_t arg3 ;
    uint32_t arg4 ;
    ccstd::vector< unsigned char > result;
    
    if(argc != 3) {
        SE_REPORT_ERROR("wrong number of arguments: %d, was expecting %d", (int)argc, 3);
        return false;
    }
    arg1 = SE_THIS_OBJECT<blk::BlkHelper>(s);
    if (nullptr == arg1) return true;
    
    ok &= sevalue_to_native(args[0], &arg2, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments"); 
    
    
    ok &= sevalue_to_native(args[1], &arg3, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    
    
    ok &= sevalue_to_native(args[2], &arg4, s.thisObject());
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    
    result = (arg1)->fill(arg2,arg3,arg4);
    
    ok &= nativevalue_to_se(result, s.rval(), s.thisObject() /*ctx*/);
    SE_PRECONDITION2(ok, false, "Error processing arguments");
    SE_HOLD_RETURN_VALUE(result, s.thisObject(), s.rval());
    
    
    
    return true;
}
SE_BIND_FUNC(js_blk_BlkHelper_fill) 

bool js_register_blk_BlkHelper(se::Object* obj) {
    auto* cls = se::Class::create("BlkHelper", obj, nullptr, _SE(js_new_blk_BlkHelper)); 
    
    cls->defineStaticProperty("__isJSB", se::Value(true), se::PropertyAttribute::READ_ONLY | se::PropertyAttribute::DONT_ENUM | se::PropertyAttribute::DONT_DELETE);
    
    cls->defineFunction("print", _SE(js_blk_BlkHelper_print)); 
    cls->defineFunction("pass", _SE(js_blk_BlkHelper_pass)); 
    cls->defineFunction("fillAsync", _SE(js_blk_BlkHelper_fillAsync)); 
    cls->defineFunction("fill", _SE(js_blk_BlkHelper_fill)); 
    
    
    
    
    cls->defineFinalizeFunction(_SE(js_delete_blk_BlkHelper));
    
    
    cls->install();
    JSBClassType::registerClass<blk::BlkHelper>(cls);
    
    __jsb_blk_BlkHelper_proto = cls->getProto();
    __jsb_blk_BlkHelper_class = cls;
    se::ScriptEngine::getInstance()->clearException();
    return true;
}




bool register_all_blk_helper(se::Object* obj) {
    // Get the ns
    se::Value nsVal;
    if (!obj->getProperty("blk", &nsVal, true))
    {
        se::HandleObject jsobj(se::Object::createPlainObject());
        nsVal.setObject(jsobj);
        obj->setProperty("blk", nsVal);
    }
    se::Object* ns = nsVal.toObject();
    /* Register classes */
    js_register_blk_BlkHelper(ns); 
    
    /* Register global variables & global functions */
    
    
    
    return true;
}


#if defined(__clang__)
#pragma clang diagnostic pop
#elif defined(__GNUC__) || defined(__GNUG__)
#pragma GCC diagnostic pop
#elif defined(_MSC_VER)
#pragma warning(pop)
#endif
// clang-format on
