/*
 * @Date: 2023-05-25 15:41:39
 * @LastEditors: Zhaozhenguo zhaozhenguoxyz@163.com
 * @LastEditTime: 2023-06-16 00:52:20
 */
export var SdkEventType = {
    NET_STATE_CHANGE:"net_state_change",
    // tcp状态的事件
    TCP_ERROR: 'tcp_error',
    TCP_CLOSE: 'tcp_close',
    TCP_OPENED: 'tcp_opened', // 连接建立好之后的回调
    TCP_RECONNECT: 'tcp_reconnect',
    TCP_RECEIVE: 'tcp_receive',//长连接接收任何消息的事件

    SDK_LOGIN_SUCCESS: 'sdk_login_success',
    SDK_LOGIN_FAIL: 'sdk_login_fail',
    WEIXIN_LOGIN_SUCCESS: 'weixin_login_success',
    WEIXIN_LOGIN_FAIL: 'weixin_login_fail',


    GET_USER_FEATURE_SUCCESS: 'GET_USER_FEATURE_SUCCESS',
    GET_USER_FEATURE_FAIL: 'GET_USER_FEATURE_FAIL',
    GET_SHARE_CONFIG_SUCCESS: 'GET_SHARE_CONFIG_SUCCESS',
    GET_SHARE_CONFIG_FAIL: 'GET_SHARE_CONFIG_FAIL',

    GET_OPEN_DATA_RESULT_SUCCESS: "GET_OPEN_DATA_RESULT_SUCCESS",
    GET_OPEN_DATA_RESULT_FAIL: "GET_OPEN_DATA_RESULT_FAIL",
    GET_OPEN_DATA_RESULT_TIMEOUT: "GET_OPEN_DATA_RESULT_TIMEOUT",

    SEND_HEART_BEAT: 'SEND_HEART_BEAT',
    GAME_SHOW: 'GAME_SHOW',
    GAME_HIDE: 'GAME_HIDE',
    START_AUTHORIZATION_SUCCESS: 'START_AUTHORIZATION_SUCCESS', //授权成功
    START_AUTHORIZATION_FAILED: 'START_AUTHORIZATION_FAILED', //授权失败

    GET_USERFEATURE_INFO_SUCCESS: 'GET_USERFEATURE_INFO_SUCCESS', //获取用户特征库信息成功
    GET_USERFEATURE_INFO_FAIL: 'GET_USERFEATURE_INFO_FAIL', //获取用户特征库信息失败

    TT_GET_CONFIG_SUCCESS:"TT_GET_CONFIG_SUCCESS",
    GET_ADMANAGER_ICON_INFO_SUCCESS: "GET_ADMANAGER_ICON_INFO_SUCCESS",     //获取交叉导流icon信息成功
    GET_ADMANAGER_BANNER_INFO_SUCCESS: "GET_ADMANAGER_BANNER_INFO_SUCCESS", //获取交叉导流banner信息成功
    GET_ADMANAGER_NEWICON_INFO_SUCCESS: "GET_ADMANAGER_NEWICON_INFO_SUCCESS",//获取交叉导流newIcon信息成功
    GO_TO_MINIGAME:"GO_TO_MINIGAME",
    GO_TO_MINIGAME_SUCCESS:"GO_TO_MINIGAME_SUCCESS",
    GO_TO_MINIGAME_FAIL:"GO_TO_MINIGAME_FAIL",
    CROSS_AD_SHOW_LIST_PLAY:"CROSS_AD_SHOW_LIST_PLAY",
    CROSS_AD_REWARD_STATE_CHANGE:"CROSS_AD_REWARD_STATE_CHANGE",
    CROSS_AD_REWARD_EXCHANGE_CHANGE:"CROSS_AD_REWARD_EXCHANGE_CHANGE",



    CREATE_PAY_ORDER_SUCCESS: "CREATE_PAY_ORDER_SUCCESS",
    CREATE_PAY_ORDER_FAIL: "CREATE_PAY_ORDER_FAIL",
    SDK_WX_PAY_SUCCESS: "SDK_WX_PAY_SUCCESS",
    SDK_WX_PAY_FAIL: "SDK_WX_PAY_FAIL",
    SET_WX_SENSITIVE_DATA_SUCCESS: "SET_WX_SENSITIVE_DATA_SUCCESS",
    SET_WX_SENSITIVE_DATA_FAIL: "SET_WX_SENSITIVE_DATA_FAIL",
    SET_WX_USER_INFO_SUCCESS: "SET_WX_USER_INFO_SUCCESS",
    SET_WX_USER_INFO_FAIL: "SET_WX_USER_INFO_FAIL",
    SDK_PAY_VERIFY_CACHE_ORDER: "SDK_PAY_VERIFY_CACHE_ORDER"
}